version: '3.8'
services:
  api:
    container_name: api
    build: .
    depends_on:
      - db
    ports:
      - '9000:8000'

  db:
    container_name: db
    image: postgres:10.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: babyloans
      POSTGRES_PASSWORD: babyloans
      POSTGRES_DB: babyloans

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  postgres-data:
    driver: local
