name: Deploy

on:
  push:
    branches:
      - main

jobs:

  create-env-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iamsauravsharma/create-dotenv@v1.2.1
        env: # env available for only this steps
          APP_ENV: prod
          APP_SECRET: ${{secrets.APP_SECRET}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_PROJECT_NAME}}          
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
